name: notion-to-markdown

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

# 実行条件
on:
  schedule:
    # 分 時 日 月 曜日 コマンド
    # TZにより、設定したい時間より9時間引く（0時に実行したい場合は15とする）
    - cron: "15 0 * * *"
  # ワークフローを手動実行可能にする
  workflow_dispatch:

# 権限設定
permissions:
  contents: write
  pull-requests: write

# ジョブ定義
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
        with:
          ref: main
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - run: npm ci
      - run: touch .env
      - run: npm run notion-fetch
        env:
          NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}
      # https://github.com/marketplace/actions/create-pull-request
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update markdown
          delete-branch: true
          title: update markdown
